name: E2E Tests

on:
  push:
    # branches:
    #   - 'main'
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v6.4.0
        with:
          go-version-file: .go-version

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          docker system prune -af

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e-repeat TEST_FOCUS="creates a Valkey Cluster deployment" TEST_REPEAT=99
          # make test-e2e-repeat TEST_FOCUS="creates a functioning cluster backed by Deployments" TEST_REPEAT=99
